# Generated by Django 4.1.2 on 2022-10-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('apartment', 'apartment'), ('shop', 'shop'), ('house', 'house'), ('studio', 'studio')], max_length=20, null=True),
        ),
    ]
