# Generated by Django 4.1.2 on 2022-10-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='reference',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
