# Generated by Django 4.1.2 on 2022-10-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_listing_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='reference',
            field=models.URLField(null=True),
        ),
    ]
